[package]
name = "primus_tfhe"
version = "0.1.0"
edition = "2024"

[dependencies]
primus_integer = { path = "../primus_integer" }
primus_reduce = { path = "../primus_reduce" }
primus_poly = { path = "../primus_poly" }
primus_fhe_core = { path = "../primus_fhe_core" }
primus_lwe = { path = "../primus_lwe" }

thiserror = { workspace = true }

[features]
default = []
simd = [
    "primus_fhe_core/simd",
    "primus_integer/simd",
    "primus_lwe/simd",
]
