[package]
name = "primus_fhe_core"
version = "0.1.0"
edition = "2024"

[dependencies]
primus_integer = { path = "../primus_integer" }
primus_reduce = { path = "../primus_reduce" }
primus_modulus = { path = "../primus_modulus" }
primus_factor = { path = "../primus_factor" }

[dev-dependencies]
primus_fft = { path = "../primus_fft" }

[features]
default = []
simd = [
    "primus_integer/simd",
    "primus_modulus/simd",
    "primus_factor/simd",
]
