[package]
name = "primus_fhe_core"
version = "0.1.0"
edition = "2024"

[dependencies]
primus_data = { path = "../primus_data" }
primus_integer = { path = "../primus_integer" }
primus_reduce = { path = "../primus_reduce" }
primus_modulus = { path = "../primus_modulus" }
primus_factor = { path = "../primus_factor" }
primus_distr = { path = "../primus_distr" }
primus_decompose = { path = "../primus_decompose" }
primus_lattice = { path = "../primus_lattice" }

thiserror = { workspace = true }
rand = { workspace = true }
zeroize = { workspace = true }
num-traits = { workspace = true }

[dev-dependencies]
primus_fft = { path = "../primus_fft" }
criterion = { workspace = true }
[[bench]]
name = "lwe_enc"
harness = false

[features]
default = []
simd = [
    "primus_integer/simd",
    "primus_modulus/simd",
    "primus_factor/simd",
    "primus_decompose/simd",
    "primus_lattice/simd",
]
