[package]
name = "primus_tfhe_glwe_ntt"
version = "0.1.0"
edition = "2024"

[dependencies]
primus_fhe_core = { path = "../primus_fhe_core" }
primus_integer = { path = "../primus_integer" }
primus_modulus = { path = "../primus_modulus" }
primus_ntt = { path = "../primus_ntt" }
primus_decompose = { path = "../primus_decompose" }

rand = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
primus_decompose = { path = "../primus_decompose" }
criterion = { workspace = true }

[[bench]]
name = "pbs"
harness = false
