[package]
name = "primus_tfhe_glwe_fourier"
version = "0.1.0"
edition = "2024"

[dependencies]
primus_data = { path = "../primus_data" }
primus_fft = { path = "../primus_fft" }
primus_fhe_core = { path = "../primus_fhe_core" }
primus_glwe = { path = "../primus_glwe" }
primus_integer = { path = "../primus_integer" }
primus_lattice = { path = "../primus_lattice" }
primus_modulus = { path = "../primus_modulus" }
primus_poly = { path = "../primus_poly" }
primus_reduce = { path = "../primus_reduce" }
primus_tfhe = { path = "../primus_tfhe" }

rand = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
primus_decompose = { path = "../primus_decompose" }
criterion = { workspace = true }

[[bench]]
name = "pbs"
harness = false
